buhrax/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'buhrax'

urlpatterns = [
    url(r'^cash/$',
        views.cash_list, name='cash_list'),
    url(r'^planned/$',
        views.cash_planned_list, name='cash_planned_list'),
    url(r'^planned/add/$',
        views.planned_cash_create, name='planned_cash_create'),
    url(r'^planned/update/(?P<pk>[0-9]+)$',
        views.planned_cash_update, name='planned_cash_update'),
    url(r'^planned/delete/(?P<pk>[0-9]+)$',
        views.planned_cash_delete, name='planned_cash_delete'),
    url(r'^update/(?P<pk>[0-9]+)$',
        views.cash_update, name='cash_update'),
    url(r'^add/$',
        views.cash_create, name='cash_create'),
    url(r'^delete/(?P<pk>[0-9]+)$',
        views.cash_delete, name='cash_delete'),
    url(r'^finance_report/$',
        views.finance_report, name='finance_report'),
    url(r'^register/',
        views.register, name='register'),
    url(r'^accounts/login/$',
        auth_views.login, name='login'),
    url(r'^accounts/profile/$',
        views.user_profile, name='user_profile'),
    url(r'^logout/$',
        views.user_logout, name='user_logout'),
]

finance/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'', include('buhrax.urls')),
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
]

buhrax/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from datetime import date
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return unicode(self.user.username)


class Types_Of_Expenses(models.Model):
    expense_name = models.CharField(max_length=200)
    expense_color = models.CharField(max_length=10)

    class Meta:
        db_table = 'buhrax_types_of_expenses'
        verbose_name = 'Типы расходов'
        verbose_name_plural = 'Типы расходов'

    def __unicode__(self):
        return unicode(self.expense_name)


class Expense(models.Model):
    expense_type = models.ForeignKey(Types_Of_Expenses)
    expenditure_name = models.CharField(max_length=200)
    description = models.CharField(
        max_length=250, default='описание статьи затрат')

    class Meta:
        db_table = 'buhrax_expense'
        verbose_name = 'Статьи расходов'
        verbose_name_plural = 'Статьи расходов'

    def __unicode__(self):
        return unicode(self.expenditure_name)


class Cash(models.Model):
    CASH_TYPE_CHOICES = (
        ('P', 'Приход'),
        ('R', 'Расход'),
    )
    cash_expense = models.ForeignKey(Expense, default=None)
    cash_date = models.DateField(default=date.today)
    cash_type = models.CharField(max_length=1, choices=CASH_TYPE_CHOICES)
    cash_value = models.FloatField(default=0.0)
    cash_desc = models.CharField(
        max_length=200, default='комментарий к движению средств')

    class Meta:
        db_table = 'buhrax_cash'
        verbose_name = 'Деньги'
        verbose_name_plural = 'Деньги'

    def __unicode__(self):
        return unicode(self.cash_expense)


class Cash_Planned(models.Model):
    PLANNED_CASH_TYPE_CHOICES = (
        ('N','Разово'),
        ('W', 'Неделя'),
        ('M', 'Месяц'),
        ('Y', 'Год')
    )
    planned_cash_expense = models.ForeignKey(Expense, default=None)
    planned_cash_date = models.DateField(default=date.today)
    planned_cash_repeat = models.CharField(max_length=1, choices=PLANNED_CASH_TYPE_CHOICES)
    planned_cash_value = models.FloatField(default=0.0)
    planned_cash_desc = models.CharField(
        max_length=200, default='комментарий к движению средств')

    class Meta:
        db_table = 'buhrax_planned_cash'
        verbose_name = 'Запланированные затраты'
        verbose_name_plural = 'Запланированные затраты'

    def __unicode__(self):
        return unicode(self.planned_cash_expense)

buhrax/views.py
# coding=utf-8
from __future__ import print_function
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Sum
from .models import Cash, UserProfile, Cash_Planned
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from datetime import datetime
import calendar



# Create your views here.

# global variables

# Forms

class CashForm(forms.ModelForm):
    class Meta:
        model = Cash
        fields = ['cash_expense', 'cash_date',
                  'cash_type', 'cash_value', 'cash_desc'
                  ]
        widgets = {
            'cash_expense': forms.Select(attrs={'class': 'form-control'}),
            'cash_date': forms.DateInput(attrs={'class': 'form-control'}),
            'cash_type': forms.Select(attrs={'class': 'form-control'}),
            'cash_value': forms.TextInput(attrs={'class': 'form-control'}),
            'cash_desc': forms.TextInput(attrs={'class': 'form-control'}),
        }

class CashPlannedFrom(forms.ModelForm):
    class Meta:
        model = Cash_Planned
        fields = ['planned_cash_expense', 'planned_cash_date', 'planned_cash_value',
                  'planned_cash_repeat','planned_cash_desc'
                  ]

        widgets = {
            'planned_cash_expense': forms.Select(attrs={'class': 'form-control'}),
            'planned_cash_date': forms.DateInput(attrs={'class': 'form-control'}),
            'planned_cash_repeat': forms.Select(attrs={'class': 'form-control'}),
            'planned_cash_value': forms.TextInput(attrs={'class': 'form-control'}),
            'planned_cash_desc': forms.TextInput(attrs={'class': 'form-control'}),
        }


class CashListSelect(forms.Form):
    year = forms.DateField(widget=forms.SelectDateWidget())
    month = forms.DateField(widget=forms.SelectDateWidget())


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')


# auth views

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    output = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}

    return render(request, 'registration/register.html', output)


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect('buhrax:cash_list')
            else:
                return HttpResponse("Your account is disabled")
        else:
            print("Invalid credentials: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'registration/login.html', {})


def user_logout(request):
    logout(request)
    return redirect('buhrax:cash_list')


@login_required
def user_profile(request):
    return redirect('buhrax:cash_list')

# cash views


@login_required
def cash_list(request):

    # if year:
    #      year = datetime,now().year
    # if month:
    #      month = datetime.now().month

    cash_total_r = Cash.objects.filter(
        cash_type="R").aggregate(Sum('cash_value'))
    cash_total_p = Cash.objects.filter(
        cash_type="P").aggregate(Sum('cash_value'))
    cash_total_z = Cash.objects.filter(
        cash_type="Z").aggregate(Sum('cash_value'))

    cash_total = cash_total_p.get(
        'cash_value__sum') - cash_total_r.get('cash_value__sum')

    years = tuple(str(n) for n in range(2010, datetime.now().year + 1))
    months = tuple(m for m in calendar.month_abbr[1:])

    cash_data = {}

    form_select = CashListSelect(request.POST or None)
    if form_select.is_valid():

        cash_data = Cash.objects.all().filter(date__year=year,
                                              date__month=month)
        return redirect('buhrax:cash_list')


    output = {'cash_data': cash_data,
              'cash_total': cash_total,
              'cash_total_p': cash_total_p,
              'cash_total_r': cash_total_r,
              'cash_total_z': cash_total_z,
              'years': years,
              'months': months,
              'form_select': form_select
              }
    return render(request, 'cash.html', output)


@login_required
def cash_create(request):
    form = CashForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('buhrax:cash_list')

    return render(request, 'edit.html', {'form': form})


@login_required
def cash_update(request, pk):
    cash_record = get_object_or_404(Cash, pk=pk)
    form = CashForm(request.POST or None, instance=cash_record)
    if form.is_valid():
        form.save()
        return redirect('buhrax:cash_list')

    return render(request, 'edit.html', {'form': form})


@login_required
def cash_delete(request, pk):
    cash_record = get_object_or_404(Cash, pk=pk)
    if request.method == 'POST':
        cash_record.delete()
        return redirect('buhrax:cash_list')

    return render(request, 'delete.html', {'object': cash_record})

# planned cash views


@login_required
def cash_planned_list(request):
    planned_cash_data = Cash_Planned.objects.order_by('planned_cash_repeat', 'planned_cash_date').all()
    planned_cash_total = Cash_Planned.objects.aggregate(Sum('planned_cash_value'))
    planned_cash_total_by_week = Cash_Planned.objects.filter(planned_cash_repeat='W').aggregate(Sum('planned_cash_value'))
    planned_cash_total_by_month = Cash_Planned.objects.filter(planned_cash_repeat='M').aggregate(Sum('planned_cash_value'))
    planned_cash_total_by_year = Cash_Planned.objects.filter(planned_cash_repeat='Y').aggregate(Sum('planned_cash_value'))

    try:
        tmp = int(planned_cash_total_by_week['planned_cash_value__sum'])
    except TypeError:
        week_result = 0
    else:
        week_result = tmp

    try:
        tmp = int(planned_cash_total_by_month['planned_cash_value__sum'])
    except TypeError:
        if week_result > 0:
            month_result = week_result * 4
    else:
        if week_result > 0:
            month_result = week_result * 4 + tmp

    try:
        tmp = int(planned_cash_total_by_year['planned_cash_value__sum'])
    except TypeError:
        if month_result > 0:
            year_result = month_result * 12
    else:
        year_result = month_result * 12 + tmp

    output = {'planned_cash_data': planned_cash_data,
              'planned_cash_total': planned_cash_total,
              'week_result': week_result,
              'month_result': month_result,
              'year_result': year_result,
              }

    return render(request, 'planned.html', output)


@login_required
def planned_cash_create(request):
    form = CashPlannedFrom(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('buhrax:cash_planned_list')

    return render(request, 'edit_planned.html', {'form': form})


@login_required
def planned_cash_update(request, pk):
    planned_cash_record = get_object_or_404(Cash_Planned, pk=pk)
    form = CashPlannedFrom(request.POST or None, instance=planned_cash_record)
    if form.is_valid():
        form.save()
        return redirect('buhrax:cash_planned_list')

    return render(request, 'edit_planned.html', {'form': form})


@login_required
def planned_cash_delete(request, pk):
    planned_cash_record = get_object_or_404(Cash_Planned, pk=pk)
    if request.method == 'POST':
        planned_cash_record.delete()
        return redirect('buhrax:cash_planned_list')

    return render(request, 'delete_planned.html', {'object': planned_cash_record})

# TODO: перенос запланированной затраты в таблицу затрат
# TODO: отметка о том что затрата перенесена в основную таблицу
# TODO: снятие отметки когда запись удалятся

@login_required
def finance_report(request):

    return render(request, 'report.html', {})

# TODO: соотношение затрат между собой
# TODO: соотношение запланированных и не запланированнох затрат

buhrax/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'style.css' %}" rel="stylesheet" />
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    {%  block scripts %}
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="{% static  'bootstrap/js/bootstrap.js' %}"></script>
    {% endblock %}

    <title>
    {% block title %}
        CASH
    {% endblock %}
    </title>
</head>

<body>
    <div class="navbar navbar-default">
        <div class="container-fluid">
            {% if user.is_authenticated%}
            <ul class="nav navbar-nav">
                <li> <a href="{% url 'buhrax:cash_list' %}">Движение денег</a> </li>
                <li> <a href="{% url 'buhrax:cash_planned_list' %}">Планирование затрат</a> </li>
                <li> <a href="{% url 'buhrax:finance_report' %}">Финансовый отчет</a> </li>
            </ul>
            {% endif %}
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">
                    {% if user.is_authenticated %}
                        {{ user.username }}!
                    {% else %}
                        Hello anonymous!
                    {% endif %}
                    </a>
                </li>

            {% if not user.is_authenticated %}
                <form id="login_form" method="post" action="/login/" class="navbar-form navbar-right">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" placeholder="Username" name="username" value="" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Password" name="password" value="" class="form-control">
                    </div>
                        <button type="submit" value="submit" class="btn btn-success">Sign in</button>
                        <a href="/register/" class="btn btn-primary">Register</a>
                </form>
            {% endif %}

            {% if user.is_authenticated %}
                <ul class="navbar-form navbar-right">
                    <a href="{% url "django.contrib.auth.views.logout" %}" class="btn btn-danger">Log Out</a>
                </ul>
            {% endif %}
            </ul>
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="footer">
        {% block footer %}
        {% endblock %}
    </div>
</body>
</html>

buhrax/templates/cash.html
{% extends "base.html" %}

{% block content %}

    <div class="panel panel-primary">
    {{ form_select.as_table }}
{#    <select name='myselect' onChange="this.form.submit();"> </select>#}

     <div>

        Текущий месяц

        <select>
            {% for m in months %}
                <option value="{{ m }}">{{ m }}</option>
            {% endfor %}
        </select>
        <select>
            {% for n in years %}
                <option value="{{ n }}">{{ n }}</option>
            {% endfor %}
        </select>

    </div>

{% if cash_data %}
    <div class="panel-heading"><h1>Таблица затрат</h1></div>
    <table class="table table-striped table-condensed">

            <tr>
                <td><strong>Дата транзакции</strong></td>
                <td><strong>Расход</strong></td>
                <td><strong>Приход</strong></td>
                <td><strong>Статья затрат</strong></td>
                <td><strong>Комментарий</strong></td>
                <td></td>
                <td></td>
            </tr>

    {% for q in cash_data %}
        {% if q.cash_type == "P" or q.cash_type == "R" %}
            <tr>
                <td>{{ q.cash_date }}</td>
                <td>{% if q.cash_type == "R" %} {{ q.cash_value }} {% endif %} </td>
                <td>{% if q.cash_type == "P" %} {{ q.cash_value }} {% endif %} </td>
                <td>{{ q.cash_expense }}</td>
                <td>{{ q.cash_desc }}</td>
                <td><a href="{% url 'buhrax:cash_update' q.pk %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                <td><a href="{% url 'buhrax:cash_delete' q.pk %}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
            </tr>
        {% endif %}
    {% endfor %}
            <tr>
                <td></td>
                <td><strong>{{ cash_total_r.cash_value__sum }}</strong></td>
                <td><strong>{{ cash_total_p.cash_value__sum }}</strong></td>
                <td><strong></strong></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
    </table>
</div>
    <div class="panel-footer">Total: {{ cash_total }}  </div>

    <div class="text-center"><a href="{% url 'buhrax:cash_create' %}" class="btn btn-success">Добавить</a></div>
{% else %}
    <p>Нет ничего для отображения</p>
{% endif %}

{% endblock %}

buhrax/templates/delete.html
{% extends "base.html" %}

{% block content %}
<form class="form-horizontal col-md-6 col-md-offset-3 text-center" method="post">{% csrf_token %}
<div class="alert alert-danger" role="alert">
    <p> Удалить запись? </p>
    <p> {{ object.cash_expense}} </p>
    <p> {{ object.cash_value }}  </p>
    <p> {{ object.cash_desc }} </p>
    <input type="submit" value="Submit" />
</div>
</form>
{% endblock %}

buhrax/templates/delete_planned.html
{% extends "base.html" %}

{% block content %}
<form class="form-horizontal col-md-6 col-md-offset-3 text-center" method="post">{% csrf_token %}
<div class="alert alert-danger" role="alert">
    <p> Удалить запись? </p>
    <p> {{ object.planned_cash_expense}} </p>
    <p> {{ object.planned_cash_value }}  </p>
    <p> {{ object.planned_cash_repeat }}  </p>
    <p> {{ object.planned_cash_desc }} </p>
    <input type="submit" value="Submit" />
</div>
</form>
{% endblock %}

buhrax/templates/edit.html
{% extends "base.html" %}

{% block content %}
            {{ form.non_field_errors }}
        <form class="form-horizontal col-md-6 col-md-offset-3" method="post">
             <div class="form-group">
                    {% csrf_token %}
                <label for="cash_expence">Статья затрат</label>
                    {{ form.cash_expence.errors }}
                    {{ form.cash_expense }}
                <label for="cash_date">Дата</label>
                    {{ form.cash_date.errors }}
                    {{ form.cash_date }}
                <label for="cash_type">Вид движения</label>
                    {{ form.cash_type.errors }}
                    {{ form.cash_type }}
                <label for="cash_type">Сумма</label>
                    {{ form.cash_value.errors }}
                    {{ form.cash_value }}
                <label for="cash_type">Описание</label>
                    {{ form.cash_desc.errors }}
                    {{ form.cash_desc }}

            </div>
            <input type="submit" value="Submit" />
        </form>
{% endblock %}

buhrax/templates/edit_planned.html
{% extends "base.html" %}

{% block content %}
            {{ form.non_field_errors }}
        <form class="form-horizontal col-md-6 col-md-offset-3" method="post">
             <div class="form-group">
                    {% csrf_token %}
                <label for="planned_cash_expense">Статья затрат</label>
                    {{ form.planned_cash_expense.errors }}
                    {{ form.planned_cash_expense }}
                <label for="planned_cash_date">Дата</label>
                    {{ form.planned_cash_date.errors }}
                    {{ form.planned_cash_date }}
                <label for="planned_cash_repeat">Периодичность</label>
                    {{ form.planned_cash_repeat.errors }}
                    {{ form.planned_cash_repeat }}
                <label for="planned_cash_value">Сумма</label>
                    {{ form.planned_cash_value.errors }}
                    {{ form.planned_cash_value }}
                <label for="planned_cash_desc">Описание</label>
                    {{ form.planned_cash_desc.errors }}
                    {{ form.planned_cash_desc }}

            </div>
            <input type="submit" value="Submit" />
        </form>
{% endblock %}

buhrax/templates/index.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

buhrax/templates/planned.html
{% extends "base.html" %}

{% block content %}

{% if planned_cash_data %}

<div class="panel panel-primary">
    <div class="panel-heading"><h1>Запланированные затраты</h1></div>
    <table class="table table-striped table-condensed">
            <tr>
                <td><strong>Дата транзакции</strong></td>
                <td><strong>Планируемый расход</strong></td>
                <td><strong>Периодичность</strong></td>
                <td><strong>Статья затрат</strong></td>
                <td><strong>Комментарий</strong></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>

    {% for q in planned_cash_data %}
            <tr>
                <td>{{ q.planned_cash_date }}</td>
                <td>{{ q.planned_cash_value }}</td>
                {% if q.planned_cash_repeat = 'W' %}
                    <td>Неделя</td>
                {% elif q.planned_cash_repeat = 'M' %}
                    <td>Месяц</td>
                {% elif q.planned_cash_repeat = 'Y' %}
                    <td>Месяц</td>
                {% endif %}
                <td>{{ q.planned_cash_expense }}</td>
                <td>{{ q.planned_cash_desc }}</td>
                <td><a href="#"><span class="glyphicon glyphicon-transfer" aria-hidden="true"></span></a></td>
                <td><a href="{% url 'buhrax:planned_cash_update' q.pk %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                <td><a href="{% url 'buhrax:planned_cash_delete' q.pk %}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
            </tr>
    {% endfor %}
            <tr>
                <td></td>
                <td><strong>
                    {{ planned_cash_total.planned_cash_value__sum }}
                </strong></td>
                <td></td>
                <td><strong></strong></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
    </table>
    <div class="panel-footer">
    <p> Сумма расходов за неделю: {{ week_result }}</p>
    <p> Сумма расходов за месяц: {{ month_result }}</p>
    <p> Сумма расходов за год: {{ year_result }}</p>
    </div>
</div>
    <div class="text-center"><a href="{% url 'buhrax:planned_cash_create' %}" class="btn btn-success">Добавить</a></div>
{% else %}
    <p>Нет ничего для отображения</p>
{% endif %}

{% endblock %}

buhrax/templates/report.html
{% extends "base.html" %}
{% block scripts %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['Mushrooms', 3],
          ['Onions', 1],
          ['Olives', 1],
          ['Zucchini', 1],
          ['Pepperoni', 2]
        ]);

        // Set chart options
        var options = {'title':'How Much Pizza I Ate Last Night',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
{%  endblock %}

{% block content %}
    <div id="chart_div"></div>
    <div class="well text-center"> Ожидается... </div>
{% endblock %}

buhrax/templates/update.html
{% extends "base.html" %}

{% block content %}
TEST
  {{cash_list}}
{% endblock %}